global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['user_service:8000']

  - job_name: 'recommendation-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['recommendation_service:8001']
