CREATE TABLE IF NOT EXISTS saga_transactions (
    id SERIAL PRIMARY KEY,
    saga_id UUID NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
